language: R
cache: packages

addons:
    apt:
        packages:
            - libudunits2-dev
            - libproj-dev
            - libgeos-dev
            - libgdal-dev
            - libmagick++-dev
            - libpoppler-cpp-dev

r_packages:
    - covr
    - lwgeom # pre-install needed for some reason?

after_success: Rscript -e "covr::codecov(line_exclusions = list(" \
                "'R/generate-maps.R', 'src/edge_thin.h', 'src/edge_thin.cpp'))"

