on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    if: "!(contains(github.event.head_commit.message, 'ci skip')||contains(github.event.head_commit.message, 'skip ci'))"
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: pandoc
        run: sudo apt-get install pandoc pandoc-citeproc
        shell: bash
      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}
        #- name: gitconfig
        #run: |
        #  sudo git config --global user.name ${{secrets.UNAME}}
        #  sudo git config --global user.email ${{secrets.EMAIL}}
      - name: Check
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
        #- name: covr
        #run: 
        #  Rscript -e "install.packages('covr')" -e "covr::codecov()"
